version: '3.0'

services:
  database:
    image: lscr.io/linuxserver/mariadb:10.6.12
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/sqlc/schema.sql:/config/initdb.d/schema.sql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
